export const messageTypes = {
	CLAIM_ADMIN_ROLE: 'CLAIM_ADMIN_ROLE',
	ADMIN_TOKEN: 'ADMIN_TOKEN',
	REVEAL_STATE_CHANGED: 'reveal-state-change',
	ROOM_UPDATE: 'ROOM_UPDATE',
	USER_INFO: 'USER_INFO',
	BRING_ME_UP_TO_SPEED: 'BRING_ME_UP_TO_SPEED',
	START_PRESENTATION: 'START_PRESENTATION',
	END_PRESENTATION: 'END_PRESENTATION',
	START_WIKIPEDIA: 'START_WIKIPEDIA',
};
